### PR TITLE
Adding daemon to manage dislib docker executions

### PR DESCRIPTION
**Pull request by kafkasl**
Now dislib can be run inside docker easily. The Readme.md contains the instructions to do so.

@javicid it would be nice if you can follow the quickstart steps and tell if there's anything wrong, difficult to understand, etc...

Issues solved:
#14

### CODE REVIEW

**Comment by kafkasl** [comment]
The docker package you installed is the old one. Please install docker-ce and try again: https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by javicid** [comment]
> The docker package you installed is the old one. Please install docker-ce and try again: https://docs.docker.com/install/linux/docker-ce/ubuntu/

You should add this to the instructions

**Comment by javicid** [comment]
After installing `docker-ce` the command `dislib init` returns this:
```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/bin/cmd.py", line 18, in _start_daemon
    all=True)
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 899, in list
    since=since)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 205, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/local/lib/python3.6/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 198, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))
```

Running `sudo dislib init` results in this:

```
Staring dislib-master container in dir /home/jalvarez/Downloads
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/create?name=dislib-master

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 766, in run
    detach=detach, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 824, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 411, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 422, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 235, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: dislib:latest")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/create?fromImage=dislib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/bin/cmd.py", line 45, in _start_daemon
    mounts=mounts, detach=True)
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 768, in run
    self.client.images.pull(image, platform=platform)
  File "/usr/local/lib/python3.6/dist-packages/docker/models/images.py", line 412, in pull
    self.client.api.pull(repository, tag=tag, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/image.py", line 399, in pull
    self._raise_for_status(response)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("pull access denied for dislib, repository does not exist or may require 'docker login'")
```

**Comment by javicid** [comment]
Just realized that having a file named `cmd.py` under `/usr/local/bin` causes really bad things to happen as it clashes with Python's cmd module.

**Comment by kafkasl** [comment]
> > The docker package you installed is the old one. Please install docker-ce and try again: https://docs.docker.com/install/linux/docker-ce/ubuntu/
> 
> You should add this to the installation instructions

The link is already there in Docker ubuntu. I've added a note to make it clearer.

**Comment by javicid** [comment]
> I forgot to change the docker image name to point to the correct one. It should be solved now.

I still get the same error.

**Pull request merged**
